{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "graph-kubernetes.labels" . | nindent 4 }}
  name: {{ template "graph-kubernetes.serviceAccountName" . }}
{{ include "graph-kubernetes.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
